// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    GLink: typeof import('./src/components/GLink.vue')['default']
    Headbar: typeof import('./src/components/Headbar.vue')['default']
    NavbarItem: typeof import('./src/components/NavbarItem.vue')['default']
    Quote: typeof import('./src/components/Quote.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
