export interface Quote {
  text: string
  author: string
}

const quotesEn: Quote[] = [
  { text: "Now I am become Death, the destroyer of worlds.", author: "J. Robert Oppenheimer" },
  { text: "If I had known, I would have become a watchmaker.", author: "Albert Einstein" },
  { text: "This is the greatest thing in history.", author: "Harry S. Truman" },
  { text: "We have done the work of the devil.", author: "J. Robert Oppenheimer" },
  { text: "The nuclear age began with a terrible flash.", author: "Linus Pauling" },
  { text: "Mankind must put an end to war.", author: "John F. Kennedy" },
  { text: "The release of atomic energy has not created a new problem.", author: "Albert Einstein" },
  { text: "It has merely made more urgent the necessity of solving an existing one.", author: "Albert Einstein" },
  { text: "We knew the world would not be the same.", author: "J. Robert Oppenheimer" },
  { text: "War is no longer a rational instrument.", author: "Dwight D. Eisenhower" },
  { text: "A nuclear war cannot be won.", author: "Ronald Reagan" },
  { text: "And it must never be fought.", author: "Ronald Reagan" },
  { text: "The survivors will envy the dead.", author: "Nikita Khrushchev" },
  { text: "Nuclear weapons are an instrument of genocide.", author: "Mikhail Gorbachev" },
  { text: "Let us never negotiate out of fear.", author: "John F. Kennedy" },
  { text: "But let us never fear to negotiate.", author: "John F. Kennedy" },
  { text: "One gun held to the temple of the entire planet.", author: "Bernard Baruch" },
  { text: "Nuclear deterrence is a balance of terror.", author: "Winston Churchill" },
  { text: "We can destroy each other many times over.", author: "Leonid Brezhnev" },
  { text: "Control over the atom is a matter of life and death.", author: "Harry S. Truman" },
  { text: "I know not with what weapons World War III will be fought.", author: "Albert Einstein" },
  { text: "But World War IV will be fought with sticks and stones.", author: "Albert Einstein" },
  { text: "The atomic bomb has destroyed the concept of a safe rear.", author: "George Orwell" },
  { text: "The sword still hangs over us.", author: "John F. Kennedy" },
  { text: "Technological progress has merely provided us with more efficient means for going backwards.", author: "Aldous Huxley" },
  { text: "We have guided missiles and misguided men.", author: "Martin Luther King Jr." },
  { text: "A world without nuclear weapons would be safer.", author: "Barack Obama" },
  { text: "The end of civilization has now become technically possible.", author: "Bertrand Russell" },
  { text: "Remember your humanity, and forget the rest.", author: "Bertrand Russell" },
  { text: "The atomic bomb is the most antisocial invention.", author: "George Bernard Shaw" },
  { text: "We hold in our hands the key to hell.", author: "Andrei Sakharov" },
  { text: "Nuclear war is absolute evil.", author: "Andrei Sakharov" },
  { text: "The atomic bomb has made war an impossible madness.", author: "Jean-Paul Sartre" },
  { text: "We have created a force that surpasses our reason.", author: "Max Born" },
  { text: "The Earth is too small for nuclear ambitions.", author: "14th Dalai Lama" },
  { text: "Nuclear weapons provide no true security.", author: "Pope Francis" },
  { text: "They only fuel fear and mistrust.", author: "Pope Francis" },
  { text: "Man has subdued the atom, but not himself.", author: "H. G. Wells" },
  { text: "We live on borrowed time.", author: "Kurt Vonnegut" },
  { text: "A nuclear arsenal is a monument to human folly.", author: "Kofi Annan" },
  { text: "There will be no victors in the radioactive ashes.", author: "Fidel Castro" },
  { text: "The bomb kills twice: first the flesh, then hope.", author: "Kenzaburō Ōe" },
  { text: "A nuclear explosion is a sun born on Earth.", author: "William L. Laurence" },
  { text: "But this sun brings only darkness.", author: "William L. Laurence" },
  { text: "We are locked in a room with a powder keg.", author: "Carl Sagan" },
  { text: "And we keep playing with matches.", author: "Carl Sagan" },
  { text: "The button is an illusion of absolute power.", author: "Charles de Gaulle" },
  { text: "Radioactivity knows no borders.", author: "Gro Harlem Brundtland" },
  { text: "The nuclear stalemate is a triumph of fear.", author: "Henry Kissinger" },
  { text: "The world must destroy the weapon before it destroys the world.", author: "John F. Kennedy" },
]

const quotesRu: Quote[] = [
  { text: "Я стал Смертью, разрушителем миров.", author: "Роберт Оппенгеймер" },
  { text: "Если бы я знал, я бы стал часовщиком.", author: "Альберт Эйнштейн" },
  { text: "Это было величайшее событие в истории.", author: "Гарри Трумэн" },
  { text: "Мы проделали работу за дьявола.", author: "Роберт Оппенгеймер" },
  { text: "Ядерный век начался с ужасной вспышки.", author: "Лайнус Полинг" },
  { text: "Человечество должно покончить с войной.", author: "Джон Кеннеди" },
  { text: "Атомная энергия не создала новую проблему.", author: "Альберт Эйнштейн" },
  { text: "Она лишь сделала более острой необходимость её решения.", author: "Альберт Эйнштейн" },
  { text: "Мы знали, что мир уже не будет прежним.", author: "Роберт Оппенгеймер" },
  { text: "Война больше не является рациональным инструментом.", author: "Дуайт Эйзенхауэр" },
  { text: "В ядерной войне не может быть победителей.", author: "Рональд Рейган" },
  { text: "И она никогда не должна быть развязана.", author: "Рональд Рейган" },
  { text: "Выжившие будут завидовать мёртвым.", author: "Никита Хрущёв" },
  { text: "Ядерное оружие — это инструмент геноцида.", author: "Михаил Горбачёв" },
  { text: "Давайте никогда не вести переговоры из страха.", author: "Джон Кеннеди" },
  { text: "Но давайте никогда не бояться вести переговоры.", author: "Джон Кеннеди" },
  { text: "Один пистолет у виска всей планеты.", author: "Бернард Барух" },
  { text: "Ядерное сдерживание — это баланс террора.", author: "Уинстон Черчилль" },
  { text: "Мы можем уничтожить друг друга многократно.", author: "Леонид Брежнев" },
  { text: "Контроль над атомом — вопрос жизни и смерти.", author: "Гарри Трумэн" },
  { text: "Не знаю, каким оружием будет вестись Третья мировая война.", author: "Альберт Эйнштейн" },
  { text: "Но Четвёртая будет вестись палками и камнями.", author: "Альберт Эйнштейн" },
  { text: "Атомная бомба уничтожила концепцию безопасного тыла.", author: "Джордж Оруэлл" },
  { text: "Меч до сих пор висит над нами.", author: "Джон Кеннеди" },
  { text: "Технологический прогресс дал нам лишь более эффективные средства для движения назад.", author: "Олдос Хаксли" },
  { text: "У нас есть управляемые ракеты и неуправляемые люди.", author: "Мартин Лютер Кинг" },
  { text: "Мир без ядерного оружия стал бы безопаснее.", author: "Барак Обама" },
  { text: "Конец цивилизации теперь стал технически возможен.", author: "Бертран Рассел" },
  { text: "Помните о своей гуманности, забудьте остальное.", author: "Бертран Рассел" },
  { text: "Атомная бомба — самое антисоциальное изобретение.", author: "Джордж Бернард Шоу" },
  { text: "Мы держим в руках ключ от ада.", author: "Андрей Сахаров" },
  { text: "Ядерная война — это абсолютное зло.", author: "Андрей Сахаров" },
  { text: "Атомная бомба сделала войну невозможным безумием.", author: "Жан-Поль Сартр" },
  { text: "Мы создали силу, превосходящую наш разум.", author: "Макс Борн" },
  { text: "Земля слишком мала для ядерных амбиций.", author: "Далай-лама XIV" },
  { text: "Ядерное оружие не даёт истинной безопасности.", author: "Папа Франциск" },
  { text: "Оно лишь подпитывает страх и недоверие.", author: "Папа Франциск" },
  { text: "Человек подчинил себе атом, но не себя.", author: "Герберт Уэллс" },
  { text: "Мы живём в долг у времени.", author: "Курт Воннегут" },
  { text: "Ядерный арсенал — это памятник человеческому безумию.", author: "Кофи Аннан" },
  { text: "Победителей в радиоактивном пепле не будет.", author: "Фидель Кастро" },
  { text: "Бомба убивает дважды: сначала плоть, потом надежду.", author: "Кэндзабуро Оэ" },
  { text: "Ядерный взрыв — это солнце, рождённое на земле.", author: "Уильям Лоуренс" },
  { text: "Но это солнце несёт только тьму.", author: "Уильям Лоуренс" },
  { text: "Мы заперты в комнате с пороховой бочкой.", author: "Карл Саган" },
  { text: "И мы продолжаем играть со спичками.", author: "Карл Саган" },
  { text: "Кнопка — это иллюзия абсолютной власти.", author: "Шарль де Голль" },
  { text: "Радиоактивность не признаёт государственных границ.", author: "Гро Харлем Брундтланд" },
  { text: "Ядерный тупик — это триумф страха.", author: "Генри Киссинджер" },
  { text: "Мир должен уничтожить оружие, пока оно не уничтожило мир.", author: "Джон Кеннеди" },
]

export function randomQuote(locale: string): Quote {
  const list = locale === "ru" ? quotesRu : quotesEn
  return list[Math.floor(Math.random() * list.length)]
}
